name: Build Wheels

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build custom build image
        if: runner.os == 'Linux'
        run: docker build -t custom-cuda-builder -f docker/cuda-on-manylinux.Dockerfile .

      - name: Install Minimal CUDA (Windows)
        if: runner.os == 'Windows'
        run: |
          curl.exe -Lo cuda_installer.exe https://developer.download.nvidia.com/compute/cuda/12.1.1/network_installers/cuda_12.1.1_windows_network.exe
          ./cuda_installer.exe -s nvcc_12.1 cudart_12.1 -log:"$PWD" -loglevel:6
          $cudaPath = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1"
          echo "CUDA_PATH=$cudaPath" >> $env:GITHUB_ENV
          echo "$cudaPath\bin" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Show CUDA Install Log
        if: always() && runner.os == 'Windows' # Runs even if the previous step failed
        run: Get-Content cuda_install.log
        shell: pwsh

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: custom-cuda-builder 
          CIBW_BUILD: "cp3*-manylinux_x86_64 cp3*-win_amd64"
          CIBW_SKIP: "cp3[0-8]-*"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair --exclude libcuda.so.1 -w {dest_dir} {wheel}"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
